//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioStore.DataAccessLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NewsId { get; set; }
        public string NewsName { get; set; }
        public string NewsImage { get; set; }
        public string NewsDiscription { get; set; }
        public System.DateTime NewsDate { get; set; }
        public string NewsOutRef { get; set; }
        public Nullable<int> NewsVisible { get; set; }
    }
}
